config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :stations

  root to: "home#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/station.rb
class Station < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :layout_by_resource

  def after_sign_in_path_for(resource)
    stations_path
  end

  private

  def layout_by_resource
    if devise_controller?
      "admin"
    else
      "application"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_station, only: [:show]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name, :description, :address, :phone, :beverage_store, :timetable)
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:index, :edit, :update, :destroy]
  layout 'admin', except: [:show]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show

  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name, :description, :address, :phone, :beverage_store, :timetable, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/home/_form.html.erb
<%= form_for(@station) do |f| %>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% @station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :beverage_store %><br>
    <%= f.text_area :beverage_store %>
  </div>
  <div class="field">
    <%= f.label :timetable %><br>
    <%= f.text_area :timetable %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home/index.html.erb
<header class="fullSection">
  <div class="container">
    <div class="pageNavigation clearAfter">

      <!-- Site Logo -->
      <div class="headerLogo">
        <%= link_to 'logo', root_path %>
      </div>

      <!-- Site Top Navigation Bar -->
      <div class="headerNav">
        <ul class="clearAfter">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Contact Us', root_path %></li>
          <li><%= link_to 'About Us', root_path %></li>
          <% if admin_signed_in? %>
              <li><%= link_to('Admin', stations_path)  %></li>
              <li><%= link_to('Logout', destroy_admin_session_path, method: :delete)  %></li>
          <% else%>
              <li><%= link_to('Login', new_admin_session_path)  %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="caption">
    <h1><span>Find your closest</span> train station</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias officiis voluptas amet libero nobis aliquid deserunt nostrum excepturi minus. Impedit, veritatis nostrum quidem in. Iusto veritatis, inventore delectus necessitatibus eveniet.</p>
  </div>
</header>



<section class="featredItems">
  <p id="notice"><%= notice %></p>
  <div class="blockTitle border">
    <h1>Stations</h1>
  </div>
  <div class="container">
    <div class="items clearAfter">
      <% counter = 0 %>
      <% @stations.each do |station| %>
          <% counter += 1
            if counter == 4
              counter = 1
            end
          %>
          <div class="item wow bounceInUp" data-wow-delay="0.<%= counter %>s">
            <div class="itemPadd">
              <div class="itemImg">
                <% if !station.image.thumb.url.nil? %>
                  <%= image_tag station.image.thumb.url, alt: "charging-station" %>
                <%else%>
                  <%= image_tag ('item.jpg') %>
                <%end%>
              </div>
              <div class="itemInfo">
                <h2><%= link_to station.name, station %></h2>
                <p><%= station.phone %></p>
              </div>
              <div class="itemMeta">
                <p><i class="fa fa-map-marker" aria-hidden="true"></i><%= station.address %></p>
              </div>
            </div>
          </div>
      <% end %>
    </div>

    <!--<div class="loadMore tac mb50">
      <button class="btn btnBlue">Load More</button>
    </div>-->
  </div>
</section>

app/views/home/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @station.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @station.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @station.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @station.phone %>
</p>

<p>
  <strong>Beverage store:</strong>
  <%= @station.beverage_store %>
</p>

<p>
  <strong>Timetable:</strong>
  <%= @station.timetable %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>

app/views/layouts/admin.erb
<!DOCTYPE html>
<html>
<head>
  <title>Train Admin</title>
  <%= csrf_meta_tags %>
  <meta name="description" content="">
  <meta name="author" content="StartUpix" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <%= stylesheet_link_tag    'application_admin', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application_admin', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyDCD3JODKwfTEB8U7OPu4UJJQN-m6UEl7o', 'data-turbolinks-track' => true %>
</head>
  <%= yield %>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Train</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>

  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyDCD3JODKwfTEB8U7OPu4UJJQN-m6UEl7o", 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>

  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Start Header Section -->


  <%= yield %>

  <footer>
    <p>Copyright © 2017 Train Stations Test Task</p>
  </footer>
</body>
</html>

app/views/shared/_header.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <nav class="navbar">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-collapse" aria-expanded="false">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse" id="nav-collapse">
            <ul class="nav navbar-nav">
              <li><a href="<%= root_path %>">Home</a></li>
              <li><%= link_to('Stations', stations_path)  %></li>
              <li><%= link_to('Add station', new_station_path)  %></a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if admin_signed_in? %>
                  <li><a href="#">Hi <%= current_admin.email %></a></li>
                  <li>
                    <%= link_to destroy_admin_session_path, method: :delete do %>
                        <i class="fa fa-sign-out" aria-hidden="true"></i>
                    <% end %>
              <% else%>
                  <%= link_to('Login', new_admin_session_path)  %>
              <% end %>
            </ul>
          </div>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/stations/_form.html.erb
<%= form_for(@station,:html => {:id => "form_station",  multipart: true})  do |f| %>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="box collPadd5">
          <div class="formTitle left">
            <h1>Details</h1>
          </div>

          <% if @station.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

                <ul>
                  <% @station.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <!-- First Row -->
          <div class="col-md-4">
            <div class="form-group">
              <%= f.text_field :name, class: "form-control", placeholder: "Station Name" %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <%= f.text_field :address, class: "form-control", id: "searchTextField", placeholder: "Station Address" %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <%= f.text_field :phone, class:"form-control",  placeholder: "Phone Number" %>
            </div>
          </div>


          <div class="col-md-12">
            <div class="fileUploader selected"> <!-- If the image is chosen add "selected" class  -->
              <%= f.file_field :image, class: 'inputfile' %>
              <%= f.label :image do %>
                <i class="fa fa-upload" aria-hidden="true"></i><span>Choose a file</span>
              <% end %>
            </div>
          </div>

          <!-- Second Row -->
          <div class="col-md-6">
            <div class="form-group">
              <%= f.text_area :description, cols:"30", rows:"10", class: "form-control", placeholder: "Station information" %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= f.text_area :beverage_store, cols:"30", rows:"10", class: "form-control", placeholder: "Beverage store information" %>
            </div>
          </div>

          <span id="timtable_container">
            <%
            if @station.id
              @timetables = JSON.parse(@station.timetable)
            else
              @timetables = []
            end
            counter = 0
            %>

            <% @timetables.each do |timetable| %>
            <% counter = counter+1 %>
              <!-- Third Row -->
              <div class="col-md-5">
                <div class="form-group">
                  <input type="text" class="form-control" data-role="name" placeholder="Train Name" value="<%= timetable[0] %>">
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group">
                  <input type="text" class="form-control" data-role="departure" placeholder="Departure" value="<%= timetable[1] %>">
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group">
                  <input type="text" class="form-control" data-role="arrival" placeholder="Arrival" value="<%= timetable[2] %>">
                </div>
              </div>
              <div class="col-md-1">
                <div class="form-group">
                  <% if counter ==1 %>
                    <button id="timetable_add" class="btn fullWidth btn-primary outline"><i class="fa fa-plus" aria-hidden="true"></i></button>
                  <% else %>
                    <button id="timetable_add" class="btn fullWidth btn-primary outline"><i class="fa fa-minus" aria-hidden="true"></i></button>
                  <% end %>
                </div>
              </div>
            <% end %>

            <% if counter ==0 %>
               <div class="col-md-5">
                <div class="form-group">
                  <input type="text" class="form-control" data-role="name" placeholder="Train Name">
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group">
                  <input type="text" class="form-control" data-role="departure" placeholder="Departure">
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group">
                  <input type="text" class="form-control" data-role="arrival" placeholder="Arrival">
                </div>
              </div>
              <div class="col-md-1">
                <div class="form-group">
                    <button id="timetable_add" class="btn fullWidth btn-primary outline"><i class="fa fa-plus" aria-hidden="true"></i></button>
                </div>
              </div>
            <% end %>
          </span>
        </div>
      </div>

      <div class="col-md-12">
        <% if @station.id %>
          <%= f.button 'Edit Station', class: "btn btn-primary right", id: 'save_btn', data: {disable_with: "Submitting..."} %>
        <% else %>
          <%= f.button 'Add Station', class: "btn btn-primary right", id: 'save_btn' %>
        <% end %>
      </div>
    </div>
  </div>
  <%= f.text_area :timetable, class: 'hidden' %>
<% end %>

app/views/stations/edit.html.erb
<body>

<%= render 'shared/header' %>

<div class="breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ol class="breadcrumb">
          <li><%= link_to('Home', root_path) %></li>
          <li><%= link_to('Stations List', stations_path) %></li>
          <li class="active"><%= @station.name %></li>
        </ol>
      </div>
    </div>
  </div>
</div>

<section class="content fromSection">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="blockTitle">
          <h1>Edit Station</h1>
        </div>
      </div>
    </div>
  </div>
  <%= render 'form' %>
</section>
</body>

app/views/stations/index.html.erb
<body>
  <%= render 'shared/header' %>
  <p id="notice"><%= notice %></p>
  <!-- Start Breadcrumbs Block -->

  <div class="breadcrumbs">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ol class="breadcrumb">
            <li><%= link_to('Home', root_path) %></li>
            <li class="active">Stations List</li>
          </ol>
        </div>
      </div>
    </div>
  </div>

  <!-- End Breadcrumbs Block -->

  <!-- Start Content Section -->

  <section class="content fromSection">
    <form action="">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-sm-6 col-xs-6">
            <div class="blockTitle">
              <h1>Stations List</h1>
            </div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-6">
            <%= link_to('Add station', new_station_path, class: "btn btn-primary right" )  %>
          </div>
          <div class="col-md-12">
            <div class="box">
              <table class="table table-bordered table-hover table-striped stations">
                <thead>
                <tr>
                  <th>Station name</th>
                  <th>Station address</th>
                  <th>Phone number</th>
                  <th>Options</th>
                </tr>
                </thead>
                <tbody>
                <% @stations.each do |station| %>
                    <tr>
                      <td><%= station.name %></td>
                      <!--<td><%= station.description %></td>-->
                      <td><%= station.address %></td>
                      <td><%= station.phone %></td>
                      <!--<td><%= station.beverage_store %></td>-->
                      <!--<td><%= station.timetable %></td>-->
                      <!--<td><%= link_to 'Show', station %></td>-->
                      <td class="options">
                        <ul class="clearAfter">
                          <li class="edit"><%= link_to 'Edit', edit_station_path(station) %></li>
                          <li class="delete"><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                        </ul>
                      </td>
                    </tr>
                <% end %>
    <!--            <tr>
                  <td>Armenia, Yerevan</td>
                  <td>+374 94 55 44 66</td>
                  <td>Lorem ipsum dolor sit amet, consectetur adipisicing elit.Beatae voluptas quidem non, <a href="" data-toggle="modal" data-target="#stationInfo">Show more</a>
                  </td>

                </tr>
    -->            </tbody>
              </table>
              <!--<div class="tableMeta clearAfter">
                <div class="metaInfo">
                  <span>Showing X of N stations</span>
                </div>
                <ul class="pagination">
                  <li>
                    <a href="#" aria-label="Previous">
                      <span aria-hidden="true"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Prev</span>
                    </a>
                  </li>
                  <li class="active"><a href="#">1</a></li>
                  <li><a href="#">2</a></li>
                  <li>
                    <a href="#" aria-label="Next">
                      <span aria-hidden="true">Next <i class="fa fa-angle-double-right" aria-hidden="true"></i></span>
                    </a>
                  </li>
                </ul>
              </div>-->
            </div>
          </div>
        </div>
      </div>
    </form>
  </section>

  <!-- End Content Section -->

  <div class="modal fade" id="stationInfo" tabindex="-1" role="dialog">
    <form action="">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Station Information</h4>
          </div>
          <div class="modal-body">
            <div class="box">
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure cum illo pariatur, perspiciatis nostrum optio sapiente aliquam provident obcaecati beatae itaque accusantium voluptas, omnis fuga tempore illum ipsa nihil fugiat!</p>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </form>
  </div>
</body>

app/views/stations/new.html.erb
<body>

  <%= render 'shared/header' %>

  <div class="breadcrumbs">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ol class="breadcrumb">
            <li><%= link_to('Home', root_path) %></li>
            <li><%= link_to('Stations List', stations_path) %></li>
            <li class="active">Add Station</li>
          </ol>
        </div>
      </div>
    </div>
  </div>

  <section class="content fromSection">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="blockTitle">
            <h1>Add Station</h1>
          </div>
        </div>
      </div>
    </div>
    <%= render 'form' %>
  </section>
</body>

app/views/stations/show.html.erb
<header class="pageHeader">
  <div class="container">

    <div class="pageNavigation clearAfter">

      <!-- Site Logo -->
      <div class="headerLogo">
        <%= link_to 'logo', root_path %>
      </div>

      <!-- Site Top Navigation Bar -->
      <div class="headerNav">
        <ul class="clearAfter">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Contact Us', root_path %></li>
          <li><%= link_to 'About Us', root_path %></li>
          <% if admin_signed_in? %>
              <li><%= link_to('Admin', stations_path)  %></li>
              <li><%= link_to('Logout', destroy_admin_session_path, method: :delete)  %></li>
          <% else%>
              <li><%= link_to('Login', new_admin_session_path)  %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>


<section class="fullInfo">
  <p id="notice"><%= notice %></p>
  <div class="fullImage" style="background-image: url('/assets/item-big.jpg')">
    <h1><%= @station.name %></h1>
  </div>

  <div class="container">
    <div class="mainInfo clearAfter">
      <div class="contactInfo">
        <div class="column">
          <div class="article">
            <h3 class="label">Station Address</h3>
            <p class="info"><i class="fa fa-map-marker" aria-hidden="true"></i><%= @station.address %></p>
          </div>

          <div class="article mt15">
            <h3 class="label">Phone Number</h3>
            <p class="info"><i class="fa fa-phone" aria-hidden="true"></i><%= @station.phone %></p>
          </div>

          <div class="article mt15">
            <h3 class="label">Station Information</h3>
            <p class="info"><i class="fa fa-info" aria-hidden="true"></i><%= @station.description %></p>
          </div>

          <div class="article mt15">
            <h3 class="label">Beverage store information</h3>
            <p class="info"><i class="fa fa-info" aria-hidden="true"></i><%= @station.beverage_store %></p>
          </div>

        </div>

        <div class="column">
          <div id="map" data-address="<%= @station.address %>" class="mt10 mb10"></div>
        </div>
      </div>

      <div class="article mt25">
        <div class="tableStyle">
          <div class="tableName">
            <h2>Timetable</h2>
          </div>
          <table border="0">
            <thead>
            <tr>
              <th><span>Train Name</span></th>
              <th><span>Departure</span></th>
              <th><span>Arrival</span></th>
            </tr>
            </thead>
            <tbody>
            <% @timetables = JSON.parse(@station.timetable) %>
            <% @timetables.each do |timetable| %>
              <tr>
                <td><%= timetable[0] %></td>
                <td>
                  <span><%= timetable[1] %></span>
                </td>
                <td>
                  <span><%= timetable[2] %></span>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>

</section>